### ISSUE TITLE
Feedback about proximity kit

### ISSUE THREAD

**Issue by JulieMallet11** [waagsociety/proximity_kit#1]
Good evening,

I'am Julie, I'am working on the MUV project with Guillem & Aitor at Fablab Barcelona. I made the proximity kit and I have a few coments. I am attaching a PDF which includes observations. 
Thank you.
Best regards
[Feedback Proximity kit.pdf](https://github.com/waagsociety/proximity_kit/files/3014882/Feedback.Proximity.kit.pdf)

**Comment by EmmaPareschi** [comment]
Hi @JulieMallet11 

thanks for the comments. 

The machinable file of PK_MUV_L1 is now updated (based on the eagle file) and I removed the 0 ohm resistor from the BOM.
In the PK_MUV you are absolutely right , R6 is 470Ohm so I updated the BOM.
About the buzzer, I didn't have the cable problem but I'm happy you found a solution.

Kind regards, Emma
